/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mychatapp;

import java.net.*;
import javax.swing.*;
import java.util.*;
import java.io.*;
import javax.swing.event.*;

/**
 *
 * @author NguyenNghiaBui
 */
public class ChatClient extends javax.swing.JFrame {
    private MyAcc acc;
    private List<MyAcc> list;
    private List<MyAcc> listOnl;
    public String[] friends;
    
    /**
     * Creates new form ChatClient
     */
    public ChatClient(MyAcc acc, List<MyAcc> list, List<MyAcc> listOnl) {
        initComponents();
        this.acc = acc;
        this.list = list;
        this.listOnl = listOnl;
        yourName.setText(acc.getUser());
        yourPort.setText(acc.getPort());
        
        List<String> temp = new ArrayList<String>();
        for (MyAcc i : list){ 
            if (temp.indexOf(i.getUser())<0){
                temp.add(i.getUser());
            }
            }
        friends = temp.toArray(new String[0]);
        System.out.println(list.size());
        listOnlFriends.setListData(friends);
    }

    private ChatClient() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yourName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        yourPort = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listOnlFriends = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        friendChat = new javax.swing.JTextField();
        btnChat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        yourName.setText("YourName");

        jLabel2.setText("Your Port");

        jLabel3.setText("Your Friends");

        listOnlFriends.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Friend 1", "Friend 2", "Friend 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listOnlFriends.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listOnlFriendsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listOnlFriends);

        btnChat.setText("Chat");
        btnChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(yourName)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yourPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(friendChat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnChat))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yourName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(yourPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(friendChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChat))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatActionPerformed
        // TODO add your handling code here:
        
        try{
            this.listOnl = updateOnl();
            String port = null;
            MyAcc desAcc = null;
            for (MyAcc a: this.list){
                if (a.getUser().equals(friendChat.getText())){
                    port = a.getPort();
                    desAcc = a;
                    break;
                }
            }
            System.out.println(port);
            int dem = 0;
            for (MyAcc a: this.listOnl){
                if (desAcc.getPort().equals(a.getPort())){
                    dem = dem + 1;
                    break;}
            }
            if (this.acc.getPort().equals(port)){
                JOptionPane.showMessageDialog(this, "You can't chat with yourself!");
            }
            else if (dem==0){
                JOptionPane.showMessageDialog(this, "Your friend is not online!");
                }
            else {  
                ChatClientForm fr = new ChatClientForm(this.acc, desAcc);
                fr.setVisible(true);
                dispose();
            }

        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Err");
        }
    }//GEN-LAST:event_btnChatActionPerformed

    private void listOnlFriendsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listOnlFriendsValueChanged
        // TODO add your handling code here:
        listOnlFriends.addListSelectionListener(new ListSelectionListener() {
            @Override
            
            public void valueChanged(ListSelectionEvent e) {
                
                friendChat.setText(friends[listOnlFriends.getSelectedIndex()]);
            }
        });
    }//GEN-LAST:event_listOnlFriendsValueChanged
    public static List<MyAcc> updateOnl() throws IOException{
        List<MyAcc> list = new ArrayList<MyAcc>();
        BufferedReader file = new BufferedReader(new FileReader("src/mychatapp/myaccOnl.txt"));
        int n = Integer.parseInt(file.readLine());
        for (int i = 0; i < n; i++)
        {
            String std = file.readLine();
            String[] in4 = std.split(";");
            MyAcc acc = new MyAcc(in4[0], in4[1], in4[2]);
            list.add(acc);
        }
        file.close();
        return list;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
                
         

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChat;
    private javax.swing.JTextField friendChat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listOnlFriends;
    private javax.swing.JLabel yourName;
    private javax.swing.JTextField yourPort;
    // End of variables declaration//GEN-END:variables
}
